dist: trusty
sudo: required
install: true
stages:
  - shell check
  - build docker images
env:
  global:
    - GOARCH=amd64
before_install:
  - sleep 15
  - sudo apt-get install -y curl shellcheck

jobs:
  include:

    - stage: shell check
      name: checking syntax of shell script
      script:
      - bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}' || true

    - stage: build byoc images
      name: build docker image byoc
      script:
      - make chaostest

notifications:
  email:
    recipients:
      - karthik.s@mayadata.io
      - sumit_nagal@intuit.com
